version: "3.8"

services:
  backend:
    container_name: app-backend
    image: app-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 8080:8080
  fronend:
    container_name: app-frontend
    image: app-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000