version: "3.8"

services:
  app:
    container_name: app-backend
    image: app-dev
    build:
      context: .
      dockerfile: Dockerfile-backend
    volumes:
      - .:/app
    ports:
      - 4000:4000