FROM golang:1.17 AS go

# Move to working directory /build
COPY . /build
WORKDIR /build

# Copy and download dependency using go mod
# COPY go.mod .
# COPY go.sum .
# RUN go mod download

# Build the application
RUN go build cmd/main.go

# # Move to /dist directory as the place for resulting binary folder
# WORKDIR /dist

# # Copy binary from build to main folder
# RUN cp /build/main .

# Export necessary port
EXPOSE 8080

# Command to run when starting the container
ENTRYPOINT [ "./main" ]